### ISSUE TITLE
`tst/testall.g` has implicit dependency on "IO" package

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/HeLP#18]
The use of `IO_FindExecutable` in tst/testall.g` leads to a warning when doing
```
gap -A tst/testall.g
```
namely
```
Syntax warning: Unbound global variable in tst/testall.g:16
if IO_FindExecutable( "zsolve" ) <> fail then
   ^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in tst/testall.g:25
if IO_FindExecutable( "zsolve" ) = fail and LoadPackage("NormalizInterface") = fail then
   ^^^^^^^^^^^^^^^^^
```

Two possible fixes come to mind:
1. add `LoadPackage("io");` before the first use of `IO_FindExecutable`
2. don't use IO for this, use built-in GAP functions instead, i.e.,  `Filename(DirectoriesSystemPrograms(), "zsolve") = fail` resp `<> fail`

**Comment by margollo** [comment]
Changed to second proposed variant. Should solve the issue
