### ISSUE TITLE
Releasing HeLP 3.5

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/HeLP#8]
Check for package updates did not pick up new release - something went wrong. To start with, the PackageInfo.g in the repository still has an old version.

It it's a matter of only running the script properly, I can run it for you - please let me know.

**Comment by margollo** [comment]
Hi Alexander,

please do or send us an instruction how to proceed. We do not know what exactly we should do. We have made the changes in PackageInfo.g in any case.

Best.
Leo

**Comment by alex-konovalov** [comment]
Hi @margollo - instructions are at https://github.com/gap-system/ReleaseTools and https://github.com/gap-system/GitHubPagesForGAP. I think we went through them last year together, but then it was a while ago... I can certainly make a release myself - with all things set up, it should be a matter of two minutes.

**Comment by margollo** [comment]
Yes, please run the strict for us. Thanks a lot.

**Comment by alex-konovalov** [comment]
OK, will do. https://github.com/gap-packages/HeLP/blob/master/PackageInfo.g still shows 3.4 and was updated a while ago, so I am puzzled by "We have made the changes in PackageInfo.g in any case" you wrote. Did you forget to push, or published a release from a branch?

Of course, I can update release date and version number now, when I will be publishing it.

**Comment by alex-konovalov** [comment]
Ok, now https://gap-packages.github.io/HeLP/ serves version 3.5 of today (I would count your old 3.5 as a release candidate). It should be picked up for testing soon. This was possible to untangle without large time losses, but only because there were no major changes in the package (code changes only involved one tests). I would strongly encourage you to not to repeat this in the future. Using GitHub allows you to commit small but logically complete changes, and then run automated tests to check that they do not break anything. If tests would fail and the commit has a number of unrelated changes, it will be difficult to see which of them broke the tests.
